/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cashmanager.main

import Initializer
import io.javalin.Javalin
import io.javalin.apibuilder.ApiBuilder.*;

fun main() {
    val init = Initializer()
    Javalin.create().routes {
        path("users") {
            get { ctx -> init.userIndexWebHandler.exec(ctx) }
            post { ctx -> init.userCreateWebHandler.exec(ctx) }
        }
        path("/purchase/{number}") {
            get { ctx -> init.accountPurchaseWebHandler.exec(ctx) }
        }
    }.start(8080)
}
