/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cashmanager.main

import Initializer
import io.javalin.Javalin

fun main() {
    val init = Initializer()
    val app = Javalin.create().start(8080)

    app.routes {
        app.get("/users") { ctx -> init.userIndexWebHandler.exec(ctx) }
        app.post("/users") { ctx -> init.userCreateWebHandler.exec(ctx) }
        app.post("/hasmoney/{number}") { ctx -> init.accountHasMoneyWebHandler.exec(ctx) }
    }
}
