/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package cashmanager.main

import Initializer
import io.javalin.Javalin

fun main() {
    val init = Initializer()
    val app = Javalin.create().start(8080)

    app.routes {
        app.get("/") { ctx -> init.userIndexWebHandler.exec(ctx) }
    }
}
